### ISSUE TITLE
29th USF soldiers (blue and grey) have both smoke grenade an stun grenade

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#233] opened 2021-09-02 12:13 UTC
**Game version:** Spearhead II 1.0.1
**Summary of bug: ** 29th USF soldiers (blue and grey) have both smoke grenade an stun grenade
**Steps to reproduce: **

1) Play USF rifle Company.
2) Train Blue and Grey USF unit

**Expected outcome: **doesn't have both grenades(?)
**Actual outcome**: It does

Reporter: Muro#4224

**Comment by Stoklomolvi** [comment] 2021-12-03 17:35
Duplicate of #231

**Closed by Stoklomolvi** 2021-12-03 17:35 UTC
Labels: bug
