### ISSUE TITLE
Panzer luchs cannot capture without Aufklärer

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#163] opened 2021-03-19 18:00 UTC
**Game Version:**  Stoklomolvi Version 1.0.7
**Summary of Bug:** Panzer luchs cannot capture without Aufklärer
**Steps to Reproduce:** 
1) Go Wehr Panzer
2) Deploy the 15. Panzergendier-division Pz.Bfw II ausf. L. 
3) Try capture point with officer unit.

**Expected Outcome:** Should be able to capture the point
**Actual Outcome:** Doesn't allow it to capture the point despite being an officer unit.

---
**Additional Information:** With the upgrade aufklärer the officer vehicle can capture but it should've work without it.
**Attachments:**

**Reporter:** Hangman#7038

![image](https://user-images.githubusercontent.com/76040686/111823332-1e2bb000-88e5-11eb-97d2-3b842f216466.png)

**Comment by Stoklomolvi** [comment] 2021-11-29 10:50
Duplicate of #66

**Closed by Stoklomolvi** 2021-11-29 10:50 UTC
Labels: bug
