### ISSUE TITLE
M4A3 HVSS 75mm has no single use HE ability

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#219] opened 2021-07-18 08:44 UTC
Game Version: spearhead 2 version 1.0.0.
Summary of Bug: m4a3 HVSS 75mm has no single use HE ability
**Steps to Reproduce:**'

1) Select American  Mechanized Doctrine
2) Build t4 building and create a M4A3 HVSS 
3) Has no HE shell Ability 

**Expected Outcome:** single use HE ability untill the t4 HE global is upgraded
**Actual Outcome:** no HE at all

**Attachments:**
![image](https://user-images.githubusercontent.com/87523678/126061272-39c9f1d5-5625-4d66-aeac-a7b206698153.png)

**Reporter:** hunter#1360

**Comment by Stoklomolvi** [comment] 2021-07-19 10:59
Duplicate of #179.

**Closed by Stoklomolvi** 2021-07-19 10:59 UTC
