### ISSUE TITLE
Leichte's free smoke dischargers for medium tanks not working. Furthermore, the grenade launcher ability is missing from the panzers IV (F1, G and H) and both command panther and panther A.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#229] opened 2021-09-02 12:07 UTC
**Game version:** Spearhead II 1.0.1
**Summary of Bug:** Leichte's free smoke dischargers for medium tanks not working. Furthermore, the grenade launcher ability is missing from the panzers IV (F1, G and H) and both command panther and panther A.
**Steps to reproduce:** 

1) Play Whermacht and pick Leichte 
2) Build any of the mentioned tanks.

**Expected outcome:** Medium tanks should start with smoke discharger ability unlocked.
**Actual outcome**: All Leichte's medium tanks miss this ability, with all panzers IV and panthers missing their base grenade launcher ability.
**Additional information:** I presume this free smoke ability is given to Leichte by giving them the Panzer Tactician upgrade for free? I also imagine Stugs would also be affected by this ability as they're labeled as medium tanks and are affected by Panzer Tactician. If that's the case, they also do not possess the free upgrade. I have also noticed that Pz. IV F1 and H only lose the grenade launchers after picking the Leichte division.

**Attachments:** 
![image](https://user-images.githubusercontent.com/87523678/131840661-4127c41d-bdff-4dd2-a828-3b7fb2ad9dec.png)

**Reporter:** Yomifer#1875

**Comment by Stoklomolvi** [comment] 2022-06-04 23:10
Duplicate of #223

**Closed by Stoklomolvi** 2022-06-04 23:10 UTC
Labels: bug
