### ISSUE TITLE
Commando Captain Rocket Strafe upgrade bugged

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#58] opened 2020-11-28 03:06 UTC
**Game Version:** latest stok patch
**Summary of Bug:** Getting the _Hawker Typhoon Rocket Strafe_ upgrade on the _4th Commando Captain Brigade Retinue_ removes both primary and secondary ability from commander and replaces them with nothing
**Steps to reproduce:**
1. go commando
2. get captain
3. get hawker typhoon rocket strafe

**Expected outcome:**
replaces the primary ability with the rocket strafe
**Actual outcome:**
both primary and secondary abilities are gone

**Attachment:**
![image](https://user-images.githubusercontent.com/19196462/100492705-ccc0a080-30fc-11eb-9376-5f41e50a6ad9.png)

**Comment by Stoklomolvi** [comment] 2020-11-28 20:09
While I appreciate the effort in reporting bugs, try to avoid reporting too many duplicates.

Duplicate of #27

**Closed by Stoklomolvi** 2020-11-28 20:09 UTC
Labels: bug
