### ISSUE TITLE
[BUG] ANZAC BG visible in FHQ without choosing doctrine

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#341] opened 2022-04-03 22:52 UTC
**Game Version:** 1.1.0.3
**Summary Of Bug:**  Persistent ANZAC battlegroup regardless of doctrine
**Steps To Reproduce:**  Build Forward HQ
**Expected Outcome:**  No battlegroups/callins are present
**Actual Outcome:**  Regardless of whether or not a doctrine has been selected or H/A has been chosen, the Heavy ANZAC battlegroup will be present in the Forward HQ, locked behind the respective doctrine

![image](https://user-images.githubusercontent.com/23408530/161452237-6d0e4873-ee0e-4281-8ef7-064901c18a1e.png)

![image](https://user-images.githubusercontent.com/23408530/161452242-84bb3a80-b2fa-4bfb-9609-c12dcb1a4b87.png)

**Reporter:** Discord user Horti-Cosmo#4378

**Comment by Luke7O7** [comment] 2022-04-07 05:06
https://github.com/Stoklomolvi/Spearhead-Public/issues/296#issue-1074279875

**Comment by Stoklomolvi** [comment] 2022-05-08 23:36
Duplicate of #296

**Closed by Stoklomolvi** 2022-05-08 23:36 UTC
Labels: bug
