### ISSUE TITLE
 USF AB glider costs no resources (same issue as ODON).

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#250] opened 2021-09-26 14:59 UTC
**Game Version:** Spearhead II 1.0.1
**Summary of Bug:** USF AB glider costs no resources (same issue as ODON).
**Steps to reproduce:** 

1) Play USF Airborne
2)Build a glider
 
**Expected outcome:** Should cost resources.
**Actual outcome:** You need the resources to drop it, but it doesn't actually use up the resources.

**Reporter:** Muro#4224

**Comment by Stoklomolvi** [comment] 2022-09-13 09:12
Duplicate of #210

**Closed** 2022-09-13 12:22 UTC
Labels: bug
