### ISSUE TITLE
Ability issue for T1 and T2 UKF Tank officers

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#84] opened 2020-12-15 21:04 UTC
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Ability not being in the right place
**Steps to Reproduce:** 
1) Go UKF Tank Hammer
2) Call in 7th Armoured Division Liutenant
3) Upgrade his secondary abilitiy recon

**Expected Outcome:** One takes place and the ability to upgrade the other is cancelled
**Actual Outcome:** One replaces the secondary ability "Smoke Barrage" and the other goes in the place of "Attack Ground" ability

---

**Additional Information:** Same thing for the 7th Armoured Captain
**Attachments:**

**Reporter:** Luke7O7#8538

![image](https://user-images.githubusercontent.com/76040686/102272270-c87bec00-3f20-11eb-91e2-422fc5273c50.png)

![image](https://user-images.githubusercontent.com/76040686/102272418-06791000-3f21-11eb-8178-2498d6006e59.png)

**Comment by Stoklomolvi** [comment] 2020-12-15 21:35
I'd consider this to be, vaguely, a duplicate of #19

**Closed by Stoklomolvi** 2020-12-15 21:35 UTC
Labels: bug
