### ISSUE TITLE
Sapper Boobytrap not working

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#175] opened 2021-05-12 21:15 UTC
**Game Version:** Stoklomolvi Version 1.0.7
**Summary of Bug:** Soviet sapper boobytrap ability for shock doc not working
**Steps to Reproduce:** 
1) Pick Soviet Shock
2) Select sapper
3) Upgrade booby trap 
4) Select one's owned point to place it

**Expected Outcome:** Boobytrap placed on point
**Actual Outcome:** Not able to place it at all

**Reporter:** ShadowIchigo#8187

**Comment by RalphRoberts** [comment] 2023-02-22 18:12
Closing as duplicate of [issue 253](https://github.com/Stoklomolvi/Spearhead-Public/issues/253) same issue but that one is better (has a picture)

**Closed** 2023-02-22 18:17 UTC
Labels: bug, duplicate
