### ISSUE TITLE
 USF TD Truck+Gun call-in from ability bar can't dismount the gun.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#198] opened 2021-07-16 14:42 UTC
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** USF TD Truck+Gun call-in from ability bar can't dismount the gun.
**Steps to Reproduce:** 

1) Select USF tank destroyer Company
2) Use the Dodge WC51 call in
3) Try to Unload the troops

**Expected Outcome:** A truck and gun working as functioning
**Actual Outcome:** Truck stops responding to any commands, doesnt move

---
**Additional Information:** Manually ordering gun to exit didnt work either. However, if the vehicle moves due to a larger vehicle trying to pass by it starts responding to commands again but still repeats the cycle when ordered to drop the gun

**Reporter:** lotus#1300

**Comment by Stoklomolvi** [comment] 2021-11-29 10:01
Duplicate of #13

**Closed by Stoklomolvi** 2021-11-29 10:01 UTC
Labels: bug
