### ISSUE TITLE
AT gun not leaving their transport (USF AT)

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#65] opened 2020-12-15 10:22 UTC
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Unit from off-map call in can't leave transport.
**Steps to Reproduce:**
1) Go US Anti-Tank
2) Use the call-in from the hotbar to call in an AT-Gun in a truck.
3) Try to get the AT-Gun to come out

**Expected Outcome:** AT-Gun leaves truck
**Actual Outcome:** AT-Gun refuses to leave truck, truck becomes unable to move.

--------------------------------------------------

**Additional Information:** None
**Attachments:** None

**Reporter:** Emifas#5368

**Comment by Stoklomolvi** [comment] 2020-12-15 12:25
Duplicate of #13

**Closed by Stoklomolvi** 2020-12-15 12:25 UTC
Labels: bug
