### ISSUE TITLE
USF Battlegroup call in with french anti tank squad spawns regular french fusiliers

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#190] opened 2021-07-16 13:44 UTC
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** USF Battlegroup call in with french anti tank squad spawns regular french fusiliers.
**Steps to Reproduce:**

1) Select USF Mechanized Comapny
2) Build forward HQ and deploy 1st Free France Division Recon Platoon
3) See squad inside M3A1 scout car

**Expected Outcome:**  Squad should be a 1re Division Française Libre AT squad
**Actual Outcome:** Deployed squad is Regular Free France fusiliers

**Reporter:** lotus#1300

**Comment by Stoklomolvi** [comment] 2023-02-07 13:40
Duplicate of #95.

**Closed by Stoklomolvi** 2023-02-07 13:40 UTC
Labels: bug
