### ISSUE TITLE
Luft airdrop gives US at gun and HMG instead of german MG42 and rakatenwerfer

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#57] opened 2020-11-23 23:42 UTC
**Gameversion:** Latest stok version
**summary of bug:** german airdrop gives a 57mm m1 at gun and 50 cal HMG instead of HMG42 and raketenwerfer.
**steps to reproduce:** 
1. go luft
2. call in the air drop (theirs two, but call in the one left of the one that mentions mortar and LEIG, it should list in its description rakatenwerfer and mg42)
**expected outcome:** HMG 42 and raketenwerfer drops
**actual outcome:** 57mm and 50cal HMG drops instead

**additional information:**
[link](https://www.youtube.com/watch?v=8LMfZok7BeY) saw it in this video, and i didnt see it as a issue yet. go to 12:40 or so too see the bug.

**Comment by Stoklomolvi** [comment] 2020-11-27 16:27
Duplicate of #26

**Closed by Stoklomolvi** 2020-11-27 16:27 UTC
Labels: bug
