### ISSUE TITLE
Lightning Strike not working

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#67] opened 2020-12-15 10:38 UTC
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Lightning Strike doesn't work (Wehr Panzer)
**Steps to Reproduce:** 

1) Go Wehr Panzer
2) Activate ability "Lightning Strike"

**Expected Outcome:** Recon planes do a quick pass over friendly Medium and Heavy armor, and nearby enemies are bombarded by 10.5 mm howitzers
**Actual Outcome:** You wasted 120 muni for nothing

---

**Additional Information:** None
**Attachments:** None

**Reporter:** Luke7O7#8538

**Comment by Stoklomolvi** [comment] 2020-12-15 12:28
Duplicate of #49

**Closed by Stoklomolvi** 2020-12-15 12:28 UTC
Labels: bug
