### ISSUE TITLE
AT Gun stuck in WC51

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#109] opened 2020-12-29 12:32 UTC
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** US tank destroyer doctrine WC51 76mm call in does not allow for the gun to exit the vehicle. The vehicle will remain stationary, waiting for the gun to leave the vehicle and will need to be killed to get the gun out.
**Steps to Reproduce:** 
1) Go US tank Destroyer doctrine
2) Call in WC51 76mm off map
3) Use the disembark button

**Expected Outcome:** AT Gun disembarks
**Actual Outcome:** Vehicle remains stationary and will never move again...

---
**Additional Information:** De-crewing or destroying the WC51 will get the decrewed gun to disembark. 

**Reporter:** Blarg_Master#1931

**Comment by Stoklomolvi** [comment] 2020-12-30 00:50
Duplicate of #13

**Closed by Stoklomolvi** 2020-12-30 00:50 UTC
