### ISSUE TITLE
Salvage operations malfunction

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#107] opened 2020-12-26 10:54 UTC
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Salvage operations malfunction
**Steps to Reproduce:**
1) Take a SS/Wehr Sturmpioneer/Pioneer with Salvage Operations available
2) Dismantle a 75mm AEC armored car

**Expected Outcome:** You can dismantle the wrecks
**Actual Outcome:** The 10 sec are displayed on the ability icon but there is no progress bar and the vehicle isn't dismantled

--- 
**Additional Information:** Duplicate of #51, AEC armored car is not dismantlable like 222s or Puma
**Attachments:** None

**Reporter:** 생선#5025

**Comment by Stoklomolvi** [comment] 2020-12-26 13:23
Duplicate of #51

**Closed by Stoklomolvi** 2020-12-26 13:23 UTC
Labels: bug
