### ISSUE TITLE
Conscript AT Grenade missing

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#79] opened 2020-12-15 17:13 UTC
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Conscript AT grenade upgrade missing
**Steps to Reproduce:** 
1) Go Soviet Union (In my case it was both SU Shock and SU Artillery)
2) Try to upgrade the AT grenade on a conscript squad
3) Try to upgrade the global AT grenade at T2

**Expected Outcome:** Either one works for the conscripts and they can use the AT grenades
**Actual Outcome:** The upgrade is missing out in the Conscript upgrade menu, and Global AT upgrade only upgrades Frontoviki's

---

**Additional Information:** Very critical bug that might be in all doctrines / non-doctrine SU ; almost duplicate of #76 
**Attachments:** None

**Reporter:** Luke7O7#8538

**Comment by Stoklomolvi** [comment] 2020-12-15 20:37
Duplicate of #76

**Closed by Stoklomolvi** 2020-12-15 20:37 UTC
Labels: bug
