### ISSUE TITLE
[BUG] Sherman "Improvised Armor" not increasing health

### ISSUE THREAD

**Issue by Luke7O7** [Stoklomolvi/Spearhead-Public#348] opened 2022-04-18 10:03 UTC
**Game Version:** Spearhead II 1.1.0.3
**Summary of Bug:** Sherman upgrade "Improvised Armor" does not increase health, but it does decrease speed.
**Steps to Reproduce:** Steps to reproduce the behavior:
1) Go USF, make an M4A2 Sherman
2) Vet it up to vet 2
3) Upgrade with "Improvised Armor"
4) See error

**Expected Outcome:** +20 Health (Bringing it up to 500 HP total, and 10% slower speed
**Actual Outcome:** No health increase, 10% slower speed.

---
**Additional Information:** First picture is without Armor, second is with it equipped (Also includes the 76mm Sherman, and probably doctrinal ones as well (Doctrinals were not tested.) Health not increased, and armor not increased (Despite it being literally called Improvised Armor who tf made this upgrade?), but speed is decreased.
**Attachments:** 
![image](https://user-images.githubusercontent.com/90381045/163792379-528cd427-c052-475c-8e6b-b01fdc6db0c5.png)

![image](https://user-images.githubusercontent.com/90381045/163792330-f4dd1e68-f179-4acc-ab5e-f07af2d7a771.png)

**Reporter:** Ya boi Kettenkrad

**Comment by Stoklomolvi** [comment] 2022-06-08 09:13
Duplicate of #345.

**Closed by Stoklomolvi** 2022-06-08 09:13 UTC
Labels: bug
