### ISSUE TITLE
US TD Dodge with M5 AT gun call in doesnt disembark AT gun

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#55] opened 2020-11-21 22:49 UTC
**Game Version:** Latest Stok Patch
**Summary of Bug:** US Tank destroyer doc, when you call in the dodge car with M5 AT gun, the AT gun refuses too get out of the car. ordering the AT gun specifically too disembark or using the disembark order on the Dodge neither work.
**Steps to reproduce:**
1. play US TD
2. call in Dodge wc51 with M5 AT gun (or maybe its WC52 idk)
3. try to disembark M5 AT gun

**Expected outcome:** M5 at gun gets out and can be used normally
**Actual outcome:** The M5 at gun doesnt get out, and the Dodge wc51 is permanently stuck in its position afterwards.

**Comment by Stoklomolvi** [comment] 2020-11-21 23:09
Duplicate of #13

**Closed by Stoklomolvi** 2020-11-21 23:09 UTC
Labels: bug
