### ISSUE TITLE
Soviet Armored Division Prizyvniki do not receive the Critical Repair ability upgrade.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#214] opened 2021-07-16 16:21 UTC
**Game Version:** SH II 1.0.0

**Summary of Bug:** Soviet Armored Division Prizyvniki do not receive the Critical Repair ability upgrade.

**Steps to Reproduce:** 

1) Pick SU armoured doctrine
2) Build A Prizyvniki squad

**Expected Outcome:** The squad will receive a 6th doctrinal upgrade.

**Actual Outcome:** The squad has no additional upgrade.

**Comment by Stoklomolvi** [comment] 2023-02-07 13:43
Duplicate of #191.

**Closed by Stoklomolvi** 2023-02-07 13:43 UTC
Labels: bug
