### ISSUE TITLE
Boost Signal Relay for Wehrmacht

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#73] opened 2020-12-15 16:38 UTC
**Game Version:** Latest Public Stok Patch
**Summary of Bug:** Boost Signal Relay not working
**Steps to Reproduce:** 
1) Go Wehr Panzer
2) Activate "Boost Signal Relays" to uncover armor in FoW

**Expected Outcome:** All armor in FoW is uncovered for several seconds
**Actual Outcome:** Nothing

---

**Additional Information:** It seems that the crew weapons are revealed, same bug with Leichte division
**Attachments:**

**Reporter:** Luke7O7#8538

![image](https://user-images.githubusercontent.com/76040686/102244008-17fbf100-3efc-11eb-873b-5ce6790efdc9.png)

**Comment by Stoklomolvi** [comment] 2020-12-15 20:37
Duplicate of #50

**Closed by Stoklomolvi** 2020-12-15 20:37 UTC
Labels: bug
